# vapt_orchestrator/llm_client.py

import os
from typing import List, Dict, Any

from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables from .env
load_dotenv()


class LLMClient:
    """
    Wrapper around Google Gemini for:
    - summarizing scan findings
    - (future) suggesting next steps, manual tests, etc.
    """

    def __init__(
        self,
        model_name: str = "gemini-2.5-flash",
    ) -> None:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise RuntimeError(
                "GEMINI_API_KEY not found. Make sure it's set in your environment or .env file."
            )

        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel(model_name)

    def _build_summary_prompt(self, target: str, findings: List[Dict[str, Any]]) -> str:
        """
        Build a prompt for the LLM to summarize the findings in a
        security-report-friendly way.
        """

        if not findings:
            return f"""
You are a security expert.

A basic network scan was run against the target `{target}` and **no open ports were identified**.

Write a short security summary explaining:
- What this means from a risk perspective
- What limitations this scan may have
- Which follow-up actions or deeper tests could still be relevant

Keep it concise, in 2–4 short paragraphs, targeting a technical but non-expert audience.
"""

        # Convert findings into a compact text table for the LLM
        findings_lines = []
        for f in findings:
            findings_lines.append(
                f"- Host: {f.get('host')}, Port: {f.get('port')}, "
                f"Protocol: {f.get('protocol')}, Service: {f.get('service')}, "
                f"Product: {f.get('product') or 'N/A'} {f.get('version') or ''}"
            )

        findings_block = "\n".join(findings_lines)

        return f"""
You are a senior VAPT (Vulnerability Assessment and Penetration Testing) expert.

You are given the results of a *basic* Nmap scan against the target `{target}`.
The scan has identified the following open ports and services:

{findings_block}

Tasks:
1. Provide a short **executive summary** (2–3 paragraphs) for a technical but non-security-expert stakeholder.
2. Highlight the **key risks** based on the exposed services (e.g., remote access, management interfaces, databases).
3. Suggest **high-level next steps** for deeper testing or hardening, but DO NOT invent vulnerabilities that are not implied.
4. Keep the tone professional and concise.

Do not include raw Nmap output; only summarize the implications and next steps.
"""

    def summarize_findings(self, target: str, findings: List[Dict[str, Any]]) -> str:
        """
        Takes normalized findings and returns a high-level human-readable summary
        generated by Gemini. Falls back to a simple non-LLM summary if anything fails.
        """
        prompt = self._build_summary_prompt(target, findings)

        try:
            response = self.model.generate_content(prompt)
            # Depending on the SDK version, .text or .candidates might be used.
            # Here we rely on .text for simplicity.
            summary = getattr(response, "text", None)
            if not summary:
                raise ValueError("LLM response did not contain text.")
            return summary.strip()
        except Exception as e:
            # Fallback: simple deterministic summary so the tool still works
            print(f"[!] LLM error: {e}")
            return self._fallback_summary(target, findings)

    def _fallback_summary(self, target: str, findings: List[Dict[str, Any]]) -> str:
        """
        Simple backup summary in case the LLM call fails.
        """

        if not findings:
            return (
                f"No open ports were identified on target `{target}` during this basic Nmap scan.\n\n"
                "From a network-exposure standpoint, this reduces the externally visible attack surface; "
                "however, it does not guarantee the absence of vulnerabilities. Additional testing such as:\n"
                "- Web application testing (if any web apps are hosted behind proxies or WAFs)\n"
                "- Authenticated internal scans\n"
                "- Configuration and hardening reviews\n"
                "may still be necessary depending on the environment and threat model."
            )

        lines = [
            f"A basic Nmap scan was performed against `{target}` and the following open services were identified:\n"
        ]

        for f in findings:
            lines.append(
                f"- {f.get('host')}:{f.get('port')} ({f.get('protocol')}) "
                f"→ {f.get('service')} {f.get('product') or ''} {f.get('version') or ''}".strip()
            )

        lines.append(
            "\nThese exposed services should be reviewed for:\n"
            "- Patch and version currency\n"
            "- Strong authentication and access control\n"
            "- Reduction of unnecessary services\n"
            "- Alignment with the principle of least privilege\n"
        )
        lines.append(
            "For a more detailed analysis, run additional vulnerability scans and targeted manual testing "
            "against the most sensitive services (e.g., remote access, databases, admin interfaces)."
        )
        return "\n".join(lines)
